using System.Collections.Generic;

namespace AssetStudio
{
    public static class CommonString
    {
        public static readonly Dictionary<uint, string> StringBuffer = new Dictionary<uint, string>
        {
            {0, "轴对齐包围盒 (AABB)"},
            {5, "动画剪辑 (AnimationClip)"},
            {19, "动画曲线 (AnimationCurve)"},
            {34, "动画状态 (AnimationState)"},
            {49, "数组 (Array)"},
            {55, "基础 (Base)"},
            {60, "位域 (BitField)"},
            {69, "位集 (bitset)"},
            {76, "布尔型 (bool)"},
            {81, "字符型 (char)"},
            {86, "RGBA 颜色 (ColorRGBA)"},
            {96, "组件 (Component)"},
            {106, "数据 (data)"},
            {111, "双端队列 (deque)"},
            {117, "双精度 (double)"},
            {124, "动态数组 (dynamic_array)"},
            {138, "快速属性名 (FastPropertyName)"},
            {155, "第一个 (first)"},
            {161, "浮点型 (float)"},
            {167, "字体 (Font)"},
            {172, "游戏对象 (GameObject)"},
            {183, "通用 Mono (Generic Mono)"},
            {196, "新渐变 (GradientNEW)"},
            {208, "全局唯一标识符 (GUID)"},
            {213, "GUI 样式 (GUIStyle)"},
            {222, "整数 (int)"},
            {226, "列表 (list)"},
            {231, "长整型 (long long)"},
            {241, "映射 (map)"},
            {245, "4x4 矩阵 (Matrix4x4f)"},
            {256, "MdFour"},
            {263, "Mono 行为 (MonoBehaviour)"},
            {277, "Mono 脚本 (MonoScript)"},
            {288, "字节大小 (m_ByteSize)"},
            {299, "曲线 (m_Curve)"},
            {307, "编辑器类标识符 (m_EditorClassIdentifier)"},
            {331, "编辑器隐藏标志 (m_EditorHideFlags)"},
            {349, "启用 (m_Enabled)"},
            {359, "扩展指针 (m_ExtensionPtr)"},
            {374, "游戏对象 (m_GameObject)"},
            {387, "索引 (m_Index)"},
            {395, "是否为数组 (m_IsArray)"},
            {405, "是否为静态 (m_IsStatic)"},
            {416, "元标志 (m_MetaFlag)"},
            {427, "名称 (m_Name)"},
            {434, "对象隐藏标志 (m_ObjectHideFlags)"},
            {452, "内部预制件 (m_PrefabInternal)"},
            {469, "预制件父对象 (m_PrefabParentObject)"},
            {490, "脚本 (m_Script)"},
            {499, "静态编辑器标志 (m_StaticEditorFlags)"},
            {519, "类型 (m_Type)"},
            {526, "版本 (m_Version)"},
            {536, "对象 (Object)"},
            {543, "对 (pair)"},
            {548, "组件指针 (PPtr<Component>)"},
            {564, "游戏对象指针 (PPtr<GameObject>)"},
            {581, "材质指针 (PPtr<Material>)"},
            {596, "Mono 行为指针 (PPtr<MonoBehaviour>)"},
            {616, "Mono 脚本指针 (PPtr<MonoScript>)"},
            {633, "对象指针 (PPtr<Object>)"},
            {646, "预制件指针 (PPtr<Prefab>)"},
            {659, "精灵指针 (PPtr<Sprite>)"},
            {672, "文本资产指针 (PPtr<TextAsset>)"},
            {688, "纹理指针 (PPtr<Texture>)"},
            {702, "2D 纹理指针 (PPtr<Texture2D>)"},
            {718, "变换指针 (PPtr<Transform>)"},
            {734, "预制件 (Prefab)"},
            {741, "四元数 (Quaternionf)"},
            {753, "矩形 (Rectf)"},
            {759, "整数矩形 (RectInt)"},
            {767, "矩形偏移 (RectOffset)"},
            {778, "第二个 (second)"},
            {785, "集合 (set)"},
            {789, "短整型 (short)"},
            {795, "大小 (size)"},
            {800, "16 位整数 (SInt16)"},
            {807, "32 位整数 (SInt32)"},
            {814, "64 位整数 (SInt64)"},
            {821, "8 位整数 (SInt8)"},
            {827, "静态向量 (staticvector)"},
            {840, "字符串 (string)"},
            {847, "文本资产 (TextAsset)"},
            {857, "文本网格 (TextMesh)"},
            {866, "纹理 (Texture)"},
            {874, "2D 纹理 (Texture2D)"},
            {884, "变换 (Transform)"},
            {894, "无类型数据 (TypelessData)"},
            {907, "16 位无符号整数 (UInt16)"},
            {914, "32 位无符号整数 (UInt32)"},
            {921, "64 位无符号整数 (UInt64)"},
            {928, "8 位无符号整数 (UInt8)"},
            {934, "无符号整数 (unsigned int)"},
            {947, "无符号长整型 (unsigned long long)"},
            {966, "无符号短整型 (unsigned short)"},
            {981, "向量 (vector)"},
            {988, "2D 向量 (Vector2f)"},
            {997, "3D 向量 (Vector3f)"},
            {1006, "4D 向量 (Vector4f)"},
            {1015, "脚本类标识符 (m_ScriptingClassIdentifier)"},
            {1042, "渐变 (Gradient)"},
            {1051, "类型指针 (Type*)"},
            {1057, "2D 整数存储 (int2_storage)"},
            {1070, "3D 整数存储 (int3_storage)"},
            {1083, "整数边界 (BoundsInt)"},
            {1093, "对应源对象 (m_CorrespondingSourceObject)"},
            {1121, "预制件实例 (m_PrefabInstance)"},
            {1138, "预制件资产 (m_PrefabAsset)"},
            {1152, "文件大小 (FileSize)"},
            {1161, "哈希值 (Hash128)"}
        };
    }
}
